[2024-03-11T16:22:47.873+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Lead_Scoring_Data_Engineering_Pipeline.mapping_interactions manual__2024-03-11T16:22:24.238896+00:00 [queued]>
[2024-03-11T16:22:47.878+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Lead_Scoring_Data_Engineering_Pipeline.mapping_interactions manual__2024-03-11T16:22:24.238896+00:00 [queued]>
[2024-03-11T16:22:47.878+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-11T16:22:47.905+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): mapping_interactions> on 2024-03-11 16:22:24.238896+00:00
[2024-03-11T16:22:47.909+0000] {standard_task_runner.py:60} INFO - Started process 1371 to run task
[2024-03-11T16:22:47.914+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_Scoring_Data_Engineering_Pipeline', 'mapping_interactions', 'manual__2024-03-11T16:22:24.238896+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_data_pipeline/lead_scoring_data_pipeline.py', '--cfg-path', '/tmp/tmpid1amwuf']
[2024-03-11T16:22:47.915+0000] {standard_task_runner.py:88} INFO - Job 45: Subtask mapping_interactions
[2024-03-11T16:22:47.949+0000] {task_command.py:423} INFO - Running <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline.mapping_interactions manual__2024-03-11T16:22:24.238896+00:00 [running]> on host 19276f21f48e
[2024-03-11T16:22:48.006+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Lead_Scoring_Data_Engineering_Pipeline' AIRFLOW_CTX_TASK_ID='mapping_interactions' AIRFLOW_CTX_EXECUTION_DATE='2024-03-11T16:22:24.238896+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-11T16:22:24.238896+00:00'
[2024-03-11T16:22:48.009+0000] {logging_mixin.py:188} INFO - Error while running interactions_mapping : Execution failed on sql 'select * from categorical_variables_mapped': no such table: categorical_variables_mapped
[2024-03-11T16:22:48.010+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-11T16:22:48.013+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=Lead_Scoring_Data_Engineering_Pipeline, task_id=mapping_interactions, execution_date=20240311T162224, start_date=20240311T162247, end_date=20240311T162248
[2024-03-11T16:22:48.044+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-11T16:22:48.055+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
