[2024-03-14T16:22:46.459+0000] {processor.py:161} INFO - Started process (PID=544) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:22:46.460+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-14T16:22:46.461+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:22:46.461+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:22:46.465+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:22:46.464+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-14T16:22:46.465+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:22:46.465+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-14T16:22:46.466+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:22:46.476+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-03-14T16:24:09.387+0000] {processor.py:161} INFO - Started process (PID=681) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:24:09.389+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-14T16:24:09.390+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:24:09.390+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:24:09.394+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:24:09.393+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-14T16:24:09.394+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:24:09.394+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-14T16:24:09.394+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:24:09.405+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-14T16:25:11.375+0000] {processor.py:161} INFO - Started process (PID=788) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:25:11.378+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-14T16:25:11.379+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:25:11.379+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:25:11.384+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:25:11.384+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-14T16:25:11.385+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:25:11.385+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-14T16:25:11.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:25:11.395+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-03-14T16:26:15.771+0000] {processor.py:161} INFO - Started process (PID=882) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:26:15.773+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-14T16:26:15.774+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:26:15.774+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:26:15.779+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:26:15.779+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-14T16:26:15.779+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:26:15.779+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-14T16:26:15.780+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:26:15.789+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-14T16:27:24.259+0000] {processor.py:161} INFO - Started process (PID=999) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:27:24.262+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-14T16:27:24.263+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:27:24.262+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:27:24.268+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:27:24.267+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-14T16:27:24.268+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:27:24.268+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-14T16:27:24.269+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:27:24.279+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-14T16:28:35.072+0000] {processor.py:161} INFO - Started process (PID=1115) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:28:35.074+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-14T16:28:35.075+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:28:35.075+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:28:35.080+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:28:35.080+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-14T16:28:35.081+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:28:35.081+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-14T16:28:35.081+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:28:35.092+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-14T16:30:14.003+0000] {processor.py:161} INFO - Started process (PID=1277) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:30:14.005+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-14T16:30:14.006+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:30:14.005+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:30:14.011+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:30:14.011+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-14T16:30:14.012+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:30:14.011+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-14T16:30:14.012+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:30:14.022+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-14T16:31:36.518+0000] {processor.py:161} INFO - Started process (PID=1425) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:31:36.520+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-14T16:31:36.521+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:31:36.521+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:31:36.527+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:31:36.526+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-14T16:31:36.527+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:31:36.527+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-14T16:31:36.527+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:31:36.538+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-14T16:32:44.527+0000] {processor.py:161} INFO - Started process (PID=1538) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:32:44.529+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-14T16:32:44.530+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:32:44.530+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:32:44.536+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:32:44.535+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-14T16:32:44.536+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:32:44.536+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-14T16:32:44.536+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:32:44.546+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-14T16:34:24.559+0000] {processor.py:161} INFO - Started process (PID=1799) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:34:24.561+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-14T16:34:24.562+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:34:24.562+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:34:24.568+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:34:24.567+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-14T16:34:24.568+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:34:24.568+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-14T16:34:24.569+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:34:24.579+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-14T16:35:39.311+0000] {processor.py:161} INFO - Started process (PID=1919) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:35:39.314+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-14T16:35:39.315+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:35:39.314+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:35:39.320+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:35:39.320+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-14T16:35:39.321+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:35:39.320+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-14T16:35:39.321+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:35:39.331+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-14T16:37:14.950+0000] {processor.py:161} INFO - Started process (PID=2095) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:37:14.952+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-14T16:37:14.953+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:37:14.952+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:37:14.958+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:37:14.958+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-14T16:37:14.959+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:37:14.958+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-14T16:37:14.959+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:37:14.969+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-14T16:38:48.878+0000] {processor.py:161} INFO - Started process (PID=2275) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:38:48.880+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-14T16:38:48.881+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:38:48.881+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:38:48.886+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:38:48.886+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-14T16:38:48.887+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:38:48.887+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-14T16:38:48.887+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:38:48.897+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-14T16:39:59.159+0000] {processor.py:161} INFO - Started process (PID=2390) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:39:59.161+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-14T16:39:59.162+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:39:59.162+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:39:59.167+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:39:59.167+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-14T16:39:59.167+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:39:59.167+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-14T16:39:59.168+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:39:59.177+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-14T16:41:08.059+0000] {processor.py:161} INFO - Started process (PID=2497) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:41:08.061+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-14T16:41:08.062+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:41:08.062+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:41:08.068+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:41:08.067+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-14T16:41:08.068+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:41:08.068+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-14T16:41:08.068+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:41:08.079+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-14T16:42:28.930+0000] {processor.py:161} INFO - Started process (PID=2613) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:42:28.933+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-14T16:42:28.934+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:42:28.933+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:42:28.939+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:42:28.939+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-14T16:42:28.940+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:42:28.940+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-14T16:42:28.940+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:42:28.950+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-14T16:43:48.915+0000] {processor.py:161} INFO - Started process (PID=2733) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:43:48.917+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-14T16:43:48.918+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:43:48.918+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:43:48.923+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:43:48.923+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-14T16:43:48.924+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:43:48.924+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-14T16:43:48.924+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:43:48.934+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-14T16:45:26.014+0000] {processor.py:161} INFO - Started process (PID=2912) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:45:26.016+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-14T16:45:26.017+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:45:26.016+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:45:26.022+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:45:26.022+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-14T16:45:26.023+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:45:26.023+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-14T16:45:26.023+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:45:26.033+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-14T16:56:04.084+0000] {processor.py:161} INFO - Started process (PID=3173) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:56:04.087+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-14T16:56:04.088+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:56:04.087+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:56:04.091+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:56:04.091+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-14T16:56:04.092+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:56:04.091+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-14T16:56:04.092+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:56:04.102+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-03-14T16:57:15.733+0000] {processor.py:161} INFO - Started process (PID=3352) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:57:15.736+0000] {processor.py:830} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-14T16:57:15.737+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:57:15.736+0000] {dagbag.py:540} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:57:15.741+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:57:15.740+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-14T16:57:15.741+0000] {logging_mixin.py:188} INFO - [2024-03-14T16:57:15.741+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-14T16:57:15.741+0000] {processor.py:842} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-14T16:57:15.754+0000] {processor.py:183} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
